name: Run UI tests
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY:  ${{ secrets.SAUCE_ACCESS_KEY }}
    steps:
      - name: install-test-pre-requisites
        uses: ./.github/actions/install-test-environment
      - name: Rake run UI tests
        env:
          CI: true
          RAILS_ENV: test
          RACK_ENV: test
          DISABLE_SPRING: 1
          CIRCLE_NODE_INDEX: 1
          CIRCLE_NODE_TOTAL: 1
          CIRCLECI: true
          LD_LIBRARY_PATH: /usr/local/lib
          CIRCLE_BUILD_NUM: "42:-2323"
          CIRCLE_TEST_REPORTS: /home/circleci/test_reports
          CIRCLE_ARTIFACTS: /home/circleci/artifacts
        run: bundle exec rake circle:run_ui_tests --trace
