name: Run integration tests
on:
  workflow_dispatch:
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: install-test-pre-requisites
        uses: ./.github/workflows/install_test_requirements.yml
      - name: Rake run UI tests
        run: bundle exec rake test:all --trace
    needs: run-ui-tests
