name: Run integration tests
on:
  workflow_dispatch:
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get actions code
        uses: actions/checkout@v3    
      - name: install-test-pre-requisites
        uses: ./.github/actions/install-test-environment
      - name: Rake run UI tests
        run: bundle exec rake test:all --trace
